version: '3.8'
services:
  ewm-gateway:
    build: ./ewm-gateway-service
    container_name: ewm_gateway_service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-main
    environment:
      - EWM_MAIN_SERVER_URL=http://ewm-main:8181

  ewm-main:
    build: ./ewm-main-service
    container_name: ewm_main_service
    ports:
      - "8181:8181"
    depends_on:
      - ewm-stats
      - main-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ewm-main-db
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore
      - EWM_STATS_SERVER_URL=http://ewm-stats:9090

  ewm-stats:
    build: ./ewm-stats-service
    container_name: ewm_stats_service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats-db
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewm_stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats-db
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore

  main-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewm_main_db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewm-main-db
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore
