spring:
  jpa:
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm-stats-db
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

server:
  port: 9090

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE
